In [7]:
import numpy as np
a=np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [8]:
b=np.arange(10,16).reshape(2,3)
print(b)

[[10 11 12]
 [13 14 15]]


In [11]:
print( np.concatenate((a,b), axis=0) )

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [12]:
print( np.concatenate((a,b), axis=1) )

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [13]:
print( np.vstack((a,b)) )

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [14]:
print( np.hstack((a,b)) )

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [15]:
print( np.stack((a,b), axis=0) )

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]]


In [16]:
print( np.stack((a,b), axis=1) )

[[[ 0  1  2]
  [10 11 12]]

 [[ 3  4  5]
  [13 14 15]]]
