In [3]:
from numpy import random

x = random.normal(size=(2, 3), loc=1, scale=2)

print(x)

[[-0.44836779  0.69861283 -4.07975426]
 [ 2.06459834  0.57566828  2.14957242]]


In [4]:
import matplotlib.pyplot as plt
#import seaborn as sns

#sns.distplot(random.normal(size=1000), hist=False)

#plt.show()

ModuleNotFoundError: No module named 'seaborn'

In [5]:
x = random.binomial(n=10, p=0.5, size=10)

print(x)

[ 5  6  4  5  7  5  7 10  5  7]
